import { extraChoiceQuestions } from "./assessment-banks";

export const careerExtension = extraChoiceQuestions([
  ["Which part of a science fair would you most enjoy?", "Testing an explanation with data", "Designing the display", "Explaining the idea to visitors", "Building the demonstration", "Pitching the project to supporters", "Organising the schedule"],
  ["A community centre needs volunteers. Which job attracts you?", "Analyse what local residents need", "Create the campaign materials", "Welcome and support visitors", "Repair and prepare equipment", "Find sponsors and partners", "Keep bookings and records accurate"],
  ["Which challenge would you choose for a weekend project?", "Investigate a puzzling result", "Make a short film", "Teach someone a new skill", "Construct something useful", "Test a small business idea", "Organise a disordered collection"],
  ["Which part of improving an app interests you most?", "Understanding why it fails", "Redesigning its experience", "Learning what users struggle with", "Getting the system working", "Deciding how it could grow", "Checking every step for errors"],
  ["You can shadow someone for a day. Which activity appeals?", "Investigating a technical question", "Developing creative concepts", "Supporting clients or learners", "Working with tools on a site", "Negotiating a proposal", "Coordinating a reliable operation"],
  ["What would make a school newspaper enjoyable?", "Checking claims and analysing trends", "Creating illustrations and layouts", "Interviewing people about their lives", "Producing the finished copies", "Promoting it and finding readers", "Managing deadlines and proofreading"],
  ["Which part of an environmental project would you take?", "Measure water or soil quality", "Design an awareness installation", "Run community conversations", "Build a practical improvement", "Recruit partners to expand it", "Track supplies and follow-up tasks"],
  ["Which problem would you rather solve?", "Why the numbers do not add up", "Why the message is uninteresting", "Why someone feels excluded", "Why a machine will not run", "Why an idea is not attracting support", "Why the process keeps missing steps"],
  ["Which achievement would you put first in a portfolio?", "A careful investigation", "An original piece of creative work", "A mentoring or service project", "Something useful I built", "An initiative I helped launch", "A complex event I organised"],
  ["Which responsibility would you choose at a sports club?", "Analyse performance patterns", "Design the club's visual identity", "Help new members settle in", "Maintain facilities and equipment", "Grow sponsorship and membership", "Manage fixtures and records"],
  ["Which task would you stay curious about even when it gets hard?", "Finding an explanation that fits the evidence", "Refining a creative idea", "Helping someone understand", "Making a reliable physical solution", "Persuading people to try an idea", "Making a complicated process orderly"],
  ["What would you enjoy contributing to a museum?", "Research objects and their history", "Design an engaging exhibition", "Guide visitors and answer questions", "Build and maintain displays", "Develop new partnerships", "Catalogue and preserve records"],
  ["Which role would you explore in food production?", "Test quality and investigate results", "Develop packaging or new concepts", "Train and support the team", "Operate and maintain equipment", "Find customers and grow the offer", "Track stock, standards and schedules"],
  ["Which task would you try next to explore a career interest?", "Analyse a public dataset", "Create a small design portfolio", "Volunteer in a tutoring programme", "Join a supervised practical workshop", "Draft and test a simple proposal", "Organise a project from start to finish"],
], ["analytical", "creative", "social", "practical", "enterprising", "structured"]);

export const subjectsExtension = extraChoiceQuestions([
  ["Which project would you choose if marks were not involved?", "Investigating a scientific question", "Planning a small enterprise", "Exploring a historical debate", "Creating an artwork", "Building a working model", "Organising a peer-support activity"],
  ["What would you contribute to a community exhibition?", "Measurements and explanations", "A budget and promotion plan", "Stories and historical context", "Visual design and displays", "Construction and equipment", "Welcoming and guiding visitors"],
  ["Which kind of reading would you choose?", "How nature or technology works", "How organisations make decisions", "How societies and languages change", "How artists develop ideas", "How to build or repair something", "How people learn and support each other"],
  ["Which part of a school garden interests you?", "Testing soil and plant growth", "Planning costs and selling produce", "Researching its community history", "Designing the space", "Installing irrigation and structures", "Teaching younger learners to participate"],
  ["What would you investigate about your town?", "Its water or energy systems", "Its shops and employment", "Its history and changing population", "Its buildings and public art", "Its transport and infrastructure", "Its learning and support services"],
  ["Which project feedback would you most like to receive?", "Your reasoning is accurate", "Your plan is commercially thoughtful", "Your argument is well supported", "Your idea is original and clear", "Your solution works reliably", "You understood people's needs"],
  ["Which task would you practise even without a test?", "Solving a challenging calculation", "Keeping records for a small project", "Writing a persuasive explanation", "Sketching and revising a design", "Making or repairing an object", "Explaining something to a classmate"],
  ["Which school club would you explore next?", "Science or coding", "Entrepreneurship or accounting", "Debate or history", "Art, drama or music", "Robotics or practical design", "Mentoring or community service"],
  ["Which question about a new product interests you?", "What makes it work?", "Who would buy it and at what cost?", "How might it change society?", "How could it look and feel better?", "How is it manufactured?", "Whose everyday problem does it solve?"],
  ["Which responsibility would you choose on a field trip?", "Record and interpret observations", "Manage the budget", "Research the location's background", "Create a visual record", "Check practical equipment", "Help the group participate comfortably"],
  ["Which topic could inspire your next presentation?", "A scientific discovery", "A business success or failure", "A social or historical issue", "A creative movement", "An engineering solution", "A community initiative"],
  ["Which challenge would make you curious?", "An unexpected experimental result", "A budget that does not balance", "Two sources telling different stories", "A design that fails to communicate", "A structure that is not stable", "A lesson that learners find confusing"],
  ["What would you rather create for a school open day?", "A science demonstration", "A fundraising plan", "A researched school history", "A poster or performance", "A practical display stand", "An activity that includes younger learners"],
  ["Which type of task do you want more exposure to?", "Mathematical and scientific reasoning", "Business and economic decisions", "Reading, writing and social analysis", "Design and creative expression", "Practical making and technical work", "Communication and helping people"],
  ["Which skill would you choose to strengthen this term?", "Working through unfamiliar problems", "Planning resources and keeping records", "Building a supported argument", "Developing and refining ideas", "Using tools and processes accurately", "Listening and explaining clearly"],
  ["Which part of a news story attracts your attention?", "The data and scientific evidence", "The financial consequences", "The social and historical context", "The photographs and storytelling", "The practical systems involved", "The effects on people's lives"],
  ["Which task would you ask a teacher to help you explore?", "A more challenging experiment", "A realistic business case study", "An extended research essay", "A creative portfolio project", "A supervised technical project", "A peer-teaching activity"],
  ["Which experience would help test your subject interests?", "A laboratory or coding workshop", "A business or finance simulation", "A debate or archive visit", "An art or design workshop", "A workshop or engineering visit", "A supervised service or teaching activity"],
], ["stem", "commerce", "humanities", "creative", "technical", "people"]);
