export type SuiteQuestion = { prompt:string; options:Array<{label:string; signal:string}> };
export type SuiteAssessment = { id:string; title:string; description:string; duration:string; premium:boolean; signals:Record<string,string>; questions:SuiteQuestion[] };
const o=(...items:Array<[string,string]>)=>items.map(([label,signal])=>({label,signal}));

export const assessmentSuite: SuiteAssessment[] = [
  { id:"career", title:"Career direction", description:"The 16-question Pathfinder assessment from the Base44 experience.", duration:"10–12 min", premium:false, signals:{analytical:"Analytical",creative:"Creative",social:"People-focused",practical:"Practical",enterprising:"Enterprising",structured:"Structured"}, questions:[
    {prompt:"It's a free Saturday afternoon. Which one are you actually doing?",options:o(["Working through a puzzle — numbers, logic, a tricky problem","analytical"],["Redesigning a poster, room or app screen in my head","creative"],["Helping a friend untangle a messy situation","social"],["Taking something apart to see how it works","practical"])},
    {prompt:"Which of these conversations could keep you listening for an hour?",options:o(["New tech, science, how things work","analytical"],["Design, art, film, music","creative"],["People's stories and what makes them tick","social"],["Money, deals, how businesses grow","enterprising"])},
    {prompt:"Which compliments do people actually give you?",options:o(["You're so good with numbers","analytical"],["You explain things really clearly","social"],["You have such a good eye","creative"],["You always win the argument","enterprising"],["You can fix anything","practical"],["You always know what to say to people","social"])},
    {prompt:"A group project is falling apart the night before. What do you instinctively do?",options:o(["List what's left, split it up, get everyone moving","structured"],["Question whether we're even answering the right brief","analytical"],["Smooth the tension so people can work","social"],["Take the hardest piece and do it myself","practical"])},
    {prompt:"Ten years from now, which life sounds best?",options:o(["Stable, secure, no financial drama","structured"],["Work that clearly helps people","social"],["Things I built that people actually use","practical"],["Senior, well-paid, moving up fast","enterprising"])},
    {prompt:"At a school reunion, what would you want to be known for?",options:o(["Being the expert everyone calls","analytical"],["Having the most interesting work","creative"],["Having genuinely helped people","social"],["Running things — leading and delivering","enterprising"])},
    {prompt:"Where does your best work happen?",options:o(["Alone, headphones on, deep focus","analytical"],["A busy team room with ideas bouncing","social"],["My own hours, wherever I happen to be","creative"],["Out of a chair — sites, wards, workshops, fields","practical"])},
    {prompt:"You're handed a new task. What do you want first?",options:o(["A clear brief and a deadline — then I'm gone","structured"],["Room to figure out my own approach","creative"],["The story behind it — whose problem is this really?","social"],["The final say on how it gets done","enterprising"])},
    {prompt:"Be honest — evenings and weekends are…",options:o(["Often work's territory","enterprising"],["Flexible when the goal matters","practical"],["Mostly protected","structured"],["Untouchable — they're mine","creative"])},
    {prompt:"The right opportunity exists — but it's in another province.",options:o(["Not worth the move","structured"],["I'd investigate the real trade-offs","analytical"],["I could move with the right support","social"],["I'm packing","enterprising"])},
    {prompt:"Maths and numbers are…",options:o(["Not my friend","creative"],["Manageable with support","social"],["Useful tools","practical"],["My comfort zone","analytical"])},
    {prompt:"Your ideal way to learn something new:",options:o(["A structured course with a syllabus and exams","structured"],["Only if it clearly leads somewhere","enterprising"],["Hands-on — trial, error, practice","practical"],["Honestly, long study paths drain me","creative"])},
    {prompt:"How clear a picture do you have of where you're heading?",options:o(["Foggy, honestly","creative"],["A few possibilities","analytical"],["A shortlist I can test","practical"],["Crystal clear","structured"])},
    {prompt:"If you had to commit to a direction today, how would that feel?",options:o(["Terrifying","social"],["Too early","analytical"],["Possible with a trial first","practical"],["Ready","enterprising"])},
    {prompt:"Studying for years to reach the role you want is…",options:o(["Not an option right now","practical"],["Possible if I can earn while studying","structured"],["Worth it for the right role","analytical"],["Worth every year","enterprising"])},
    {prompt:"A free online course appears in your feed. What usually happens?",options:o(["Saved, started and finished","structured"],["I do better with a class, classmates and deadlines","social"],["I'd rather shadow someone doing the real thing","practical"],["Honestly? I scroll past","creative"])},
  ]},
  { id:"subjects", title:"Subject choice intensive", description:"For Grades 7–9: connect strengths and preferred activities to a Grade 10 subject shortlist.", duration:"12–15 min", premium:true, signals:{stem:"STEM",commerce:"Commerce",humanities:"Humanities",creative:"Creative",technical:"Technical",people:"People & service"}, questions:[
    ["Which task makes time disappear?",[["Solving a number pattern","stem"],["Planning a small sale","commerce"],["Writing or debating an idea","humanities"],["Making or designing something","creative"]]],
    ["Which school problem would you volunteer to solve?",[["A broken device","technical"],["A confusing budget","commerce"],["A conflict between classmates","people"],["An unclear poster or message","creative"]]],
    ["Which evidence do you trust most?",[["Measurements and experiments","stem"],["Costs and results","commerce"],["People's experiences and history","humanities"],["A working prototype","technical"]]],
    ["What kind of homework feels most satisfying?",[["One correct answer after hard reasoning","stem"],["A case study with a decision","commerce"],["An essay with a strong argument","humanities"],["A visual or practical submission","creative"]]],
    ["Which environment sounds most interesting?",[["Laboratory or engineering team","stem"],["Business or finance team","commerce"],["Courtroom, newsroom or public service","humanities"],["Studio, workshop or site","technical"]]],
    ["When helping someone, what comes naturally?",[["Explaining the logic","stem"],["Organising the plan","commerce"],["Listening and understanding","people"],["Showing them physically","technical"]]],
    ["How do you feel about advanced Mathematics?",[["I enjoy the challenge","stem"],["I can commit with support","commerce"],["I prefer language and social questions","humanities"],["I prefer practical calculation","technical"]]],
    ["Which topic would you research without being asked?",[["Space, health or technology","stem"],["Markets, money or brands","commerce"],["Politics, society or law","humanities"],["Buildings, machines or visual design","creative"]]],
    ["Which result would make you proudest?",[["A correct model","stem"],["A successful plan","commerce"],["A persuasive explanation","humanities"],["A useful thing I made","technical"]]],
    ["What feedback helps you most?",[["Show me the error in my method","stem"],["Show me how to improve the outcome","commerce"],["Challenge my reasoning","humanities"],["Let me revise the design","creative"]]],
    ["Which responsibility would you take in a school event?",[["Technical setup","technical"],["Money and logistics","commerce"],["People and communication","people"],["Theme and visuals","creative"]]],
    ["What do you want to keep open after Grade 12?",[["Science, engineering or health","stem"],["Business, accounting or economics","commerce"],["Law, education or social sciences","humanities"],["Design, media or skilled trades","creative"]]],
  ].map(([prompt,options])=>({prompt:prompt as string,options:(options as string[][]).map(([label,signal])=>({label,signal}))}))},
  { id:"leadership", title:"Leadership", description:"Pressure, delegation, accountability, influence and decision-making.", duration:"8–10 min", premium:true, signals:{strategic:"Strategic",coach:"Coaching",decisive:"Decisive",collaborative:"Collaborative"}, questions:makeScale("leadership",["A deadline moves forward unexpectedly.","Two strong teammates disagree.","A quieter person has not contributed.","Your plan is failing in public.","You must delegate important work.","The group wants a popular but weak option.","Someone misses a commitment.","You inherit an unclear goal.","The team succeeds.","You realise you were wrong."],["strategic","coach","decisive","collaborative"])},
  { id:"personality", title:"Personality & work style", description:"Energy, structure, curiosity, resilience and preferred work context.", duration:"8–10 min", premium:true, signals:{focused:"Focused",social:"Social",adaptable:"Adaptable",driven:"Driven"}, questions:makeScale("work",["After a busy week, how do you recharge?","How much routine helps you perform?","A plan changes at the last minute.","You receive blunt feedback.","You enter a room where you know nobody.","A task has no clear answer.","Your workload suddenly doubles.","You have a bold new idea.","You disagree with a senior person.","Success will take months of repetition."],["focused","social","adaptable","driven"])},
  { id:"learning", title:"Learning style", description:"How you absorb, practise, remember and apply new material.", duration:"8–10 min", premium:true, signals:{visual:"Visual",verbal:"Verbal",practice:"Hands-on",reflective:"Reflective"}, questions:makeScale("learning",["A difficult concept is introduced.","You need to remember a process.","An exam is two weeks away.","You make the same mistake twice.","A teacher moves too quickly.","You start unfamiliar software.","You need to explain an idea.","A chapter feels abstract.","You have one hour to revise.","You want to master a skill."],["visual","verbal","practice","reflective"])},
  { id:"eq", title:"Emotional intelligence", description:"Self-awareness, empathy, regulation and relationship judgement.", duration:"10–12 min", premium:true, signals:{awareness:"Self-awareness",empathy:"Empathy",regulation:"Regulation",relationships:"Relationships"}, questions:makeScale("EQ",["You feel irritated during a meeting.","A friend says they're fine but looks upset.","You receive criticism you think is unfair.","Someone interrupts you repeatedly.","Your group is anxious before a deadline.","You disappoint someone.","A conflict follows you home.","A teammate reacts emotionally.","You need to give difficult feedback.","You notice your motivation dropping."],["awareness","empathy","regulation","relationships"])},
];

function makeScale(context:string,prompts:string[],signals:string[]):SuiteQuestion[]{
  return prompts.map((prompt,index)=>({prompt,options:o([`Pause and examine what is happening`,signals[index%signals.length]],[`Talk it through and include other perspectives`,signals[(index+1)%signals.length]],[`Choose a clear action and move`,signals[(index+2)%signals.length]],[`Adapt the plan and test a better response`,signals[(index+3)%signals.length]])}));
}
