import type { SuiteQuestion, SuiteAssessment } from "./assessment-suite";

// Every choice keeps its meaning across contexts. These are exploratory,
// forced-choice reflections, not standardised psychometric instruments.
type Block = [contexts: string[], choices: string[]];
function contextualQuestions(signals: string[], blocks: Block[]): SuiteQuestion[] {
  return blocks.flatMap(([contexts, choices]) => contexts.map(context => ({
    prompt: `${context} Which response is closest to yours?`,
    options: choices.map((label, i) => ({ label, signal: signals[i] })),
  })));
}
function bank(id: string, title: string, description: string, signals: Record<string,string>, blocks: Block[]): SuiteAssessment {
  return { id, title, description, signals, duration: "12–15 min", premium: true, questions: contextualQuestions(Object.keys(signals), blocks) };
}

export const deeperAssessments: SuiteAssessment[] = [
  bank("leadership", "Leadership", "Explore strategy, coaching, decisions and collaboration across five leadership situations.", {strategic:"Strategic",coach:"Coaching",decisive:"Decisive",collaborative:"Collaborative"}, [
    [["Your group has a week to organise a school event.","A project starts without clear instructions.","You lead people who have never worked together.","A team has more ideas than time.","You inherit a project halfway through.","Your group must choose between two worthwhile goals."], ["Map the goal, constraints and milestones.","Find out what each person needs to contribute.","Choose a workable direction and assign the first tasks.","Build a shared plan with the whole group."]],
    [["A teammate struggles with their assigned task.","A new member is afraid to ask questions.","Someone keeps missing their deadlines.","An experienced member wants a bigger challenge.","You need to hand over an important responsibility.","One person is doing most of the work."], ["Review roles and how the tasks depend on each other.","Offer guidance and agree on a development step.","Set a clear expectation and follow-up deadline.","Discuss how the group can share the work fairly."]],
    [["Two members argue about the best approach.","Your team disagrees with your proposal.","A popular idea does not meet the brief.","A quiet member challenges the group.","You must work with a team you do not know.","A partner organisation wants a different outcome."], ["Compare the proposals against the goal and evidence.","Help each person explain their concerns.","Make a decision and explain the responsibility I take.","Look for an agreement everyone can support."]],
    [["A key resource becomes unavailable.","Your event loses its venue.","A deadline is brought forward.","Your first attempt fails in public.","The team receives unexpected criticism.","A key member cannot attend."], ["Reassess risks and revise the plan.","Check how people are coping and support them.","Pick the most urgent action and get moving.","Bring the team together to design a response."]],
    [["Your team finishes a difficult project.","You realise your decision caused a problem.","A group achievement gets public attention.","You prepare a handover to next year's leaders.","A teammate offers feedback about your leadership.","You are asked what the team should improve next."], ["Review what the evidence says about our approach.","Recognise individual growth and discuss support.","Own the outcome and commit to a specific change.","Invite everyone to reflect and agree on lessons."]],
  ]),
  bank("personality", "Personality & work style", "Reflect on energy, concentration, change, ambition and collaboration.", {focused:"Focused",social:"Social",adaptable:"Adaptable",driven:"Driven"}, [
    [["You can choose how to spend a free project afternoon.","A new team asks where you work best.","You plan a demanding week.","You return after a busy school day.","You choose between several volunteering roles.","You decide how to spend an uninterrupted morning."], ["I want a quiet space and one absorbing task.","I want company and chances to exchange ideas.","I want variety and room to switch approaches.","I want a challenging target to work towards."]],
    [["You begin an assignment with a broad brief.","You prepare for a competition.","You learn a new responsibility.","You face a task that will take several weeks.","You join a club with unfamiliar routines.","You choose your role in a group presentation."], ["I prefer enough time to understand the details.","I prefer discussing the task as I work.","I prefer experimenting before settling on a method.","I prefer clear goals that stretch my ability."]],
    [["Your schedule changes suddenly.","A familiar tool is replaced.","You are moved to a different team.","The rules of a project change halfway through.","A planned opportunity falls through.","You are asked to try an unfamiliar activity."], ["I need a little space to work through the change.","Talking to someone helps me settle.","I become curious about the new possibilities.","I focus on how to keep making progress."]],
    [["Someone critiques your work.","You make a mistake during a presentation.","A test result is lower than you hoped.","Your team compares different solutions.","You meet a person with a different viewpoint.","You receive an unexpected suggestion."], ["I think it through privately before responding.","I want a conversation to understand it.","I am willing to test a different approach.","I want a specific improvement target."]],
    [["You consider what makes a project satisfying.","You choose a holiday activity.","You imagine a good working week.","You decide which achievement matters to you.","You choose an extracurricular commitment.","You look back on an enjoyable task."], ["Having time to produce careful, thoughtful work.","Feeling connected to the people involved.","Discovering something different or unexpected.","Achieving a difficult goal and seeing progress."]],
  ]),
  bank("learning", "Learning strategies", "Compare ways to understand, practise, recall and check learning. Preferences are flexible.", {visual:"Diagrams & examples",verbal:"Explanation & discussion",practice:"Practice & application",reflective:"Reflection & review"}, [
    [["You encounter a difficult scientific concept.","You need to understand a historical sequence.","You learn how a business process works.","You study a new mathematical method.","You begin a geography topic.","You are introduced to an unfamiliar computer system."], ["Start with a diagram or worked example.","Hear an explanation and ask questions.","Try a small task using the idea.","Read slowly and write down what I understand."]],
    [["You need to remember a set of key terms.","You revise a process for a test.","You prepare to describe a case study.","You review the steps in a calculation.","You learn the structure of an essay.","You review a practical procedure."], ["Recreate a diagram or visual outline from memory.","Explain the material aloud without my notes.","Answer practice questions without looking up answers.","Recall the material, then check gaps in my notes."]],
    [["You keep making the same calculation error.","A chapter seems confusing.","A practice answer receives poor feedback.","You cannot follow a lesson at its current pace.","You forget a method you used last month.","You do not understand why an experiment failed."], ["Compare my work with an annotated example.","Ask someone to explain the point I am missing.","Retry a simpler example and build up gradually.","Trace my reasoning and record where it breaks down."]],
    [["You start learning unfamiliar software.","You need to prepare a speech.","You learn a new workshop technique.","You want to apply a formula to a real problem.","You practise analysing a source.","You learn to interpret a new type of graph."], ["Study a demonstration and map its steps.","Discuss the method with someone experienced.","Attempt it myself and use feedback to adjust.","Plan the steps, try them, then review the outcome."]],
    [["You have a week before an exam.","You have one hour to revise a topic.","You are planning a study group session.","You want to check whether you really understand.","You return to material after a long break.","You need to teach a concept to a classmate."], ["Draw a summary from memory and check accuracy.","Explain the topic and invite questions.","Use a varied set of practice problems.","Test myself, then revisit only the weak areas."]],
  ]),
  bank("eq", "Emotional intelligence", "Explore the responses you favour around emotions, empathy, regulation and relationships.", {awareness:"Self-awareness",empathy:"Empathy",regulation:"Regulation",relationships:"Relationships"}, [
    [["You feel irritated during a group task.","You are nervous before a presentation.","You lose motivation after a setback.","You feel left out of a conversation.","You feel jealous of a friend's achievement.","You are overwhelmed by competing deadlines."], ["Name the feeling and consider what triggered it.","Consider what the other people may be experiencing.","Pause and calm myself before choosing a response.","Talk to someone involved about what would help."]],
    [["A friend says they are fine but looks upset.","A teammate withdraws from a discussion.","Someone reacts strongly to a small mistake.","A classmate seems anxious about their future.","A friend is disappointed after an interview.","A new team member looks uncomfortable."], ["Notice my own assumptions before responding.","Ask how they feel and listen without jumping in.","Stay calm and give them room to respond.","Offer a supportive conversation and agree on help."]],
    [["Someone interrupts you repeatedly.","You receive criticism that feels unfair.","A group chat becomes heated.","A disagreement follows you home.","A teammate blames you for a shared mistake.","You need to respond to a rude comment."], ["Separate what happened from my interpretation.","Try to understand what is behind their reaction.","Take a pause before replying.","Set a respectful boundary and discuss a way forward."]],
    [["You have disappointed a friend.","You must give difficult feedback.","You disagree with someone you respect.","You need to ask for support.","You notice tension between two teammates.","You want to repair a misunderstanding."], ["Be clear with myself about my feelings and needs.","Invite their perspective before explaining mine.","Choose a calm time and manage my tone.","Have a direct conversation about how to move forward."]],
    [["You reflect after a difficult group project.","You prepare for a stressful week.","You notice a pattern in your arguments.","You celebrate success after a demanding task.","You think about a relationship that has improved.","You consider how you react under pressure."], ["Look for patterns in my own emotional responses.","Think about what the experience was like for others.","Identify routines that help me respond calmly.","Discuss what we can do differently together."]],
  ]),
  bank("values", "Work values & lifestyle", "Explore the trade-offs between security, growth, contribution and independence.", {security:"Security",growth:"Growth",contribution:"Contribution",independence:"Independence"}, [
    [["You compare two appealing career routes.","You choose a first holiday job.","You consider a long-term project.","You imagine a satisfying working life.","You choose between two volunteering roles.","You decide what makes an opportunity worthwhile."], ["Predictability and reliable expectations matter most.","Learning and room to develop matter most.","The benefit to other people matters most.","Freedom to shape my own work matters most."]],
    [["You choose the kind of organisation to join.","You compare a small team with a large employer.","You decide which mentor to learn from.","You consider joining a new community project.","You choose an internship environment.","You decide where you could stay motivated."], ["I value stability and dependable support.","I value feedback and challenging opportunities.","I value a purpose I believe in.","I value ownership and room for initiative."]],
    [["An opportunity would require moving away.","A role asks for some weekend work.","A study route takes longer than expected.","You consider a project with uncertain results.","You are offered a responsibility that changes your routine.","You compare a familiar route with an unusual one."], ["Protecting a stable routine is my main concern.","The skills I could gain are my main consideration.","Whether the work helps others is my main consideration.","Whether I have control over the choice matters most."]],
    [["You are asked what recognition you would appreciate.","You look back on a difficult achievement.","You choose a personal goal for next year.","You describe why a task felt meaningful.","You think about what would keep you in a role.","You decide how to judge your own progress."], ["Feeling more secure and prepared.","Becoming more capable at something difficult.","Knowing that someone benefited from my effort.","Having more freedom to choose my direction."]],
    [["You must turn down one attractive opportunity.","You discuss priorities with your family.","You plan how to spend limited free time.","You review a career idea that no longer fits.","You choose a compromise between two goals.","You think about your non-negotiables at work."], ["I would protect dependable conditions first.","I would protect opportunities to keep learning first.","I would protect work that contributes to others first.","I would protect the ability to make my own choices first."]],
  ]),
  bank("enterprise", "Employment & entrepreneurship", "Reflect on how you approach customers, delivery, uncertainty and building with others.", {research:"Research first",delivery:"Delivery focus",experiment:"Small experiments",team:"Team & support"}, [
    [["You have an idea for a small service.","Friends suggest selling something at school.","You notice a problem in your community.","A club wants to raise funds.","You consider turning a hobby into paid work.","Someone asks whether your idea could become a business."], ["Find out who has the problem and what they already use.","Work out what I can reliably deliver.","Try a small, low-cost version before committing.","Find people whose skills and support complement mine."]],
    [["Someone says your idea will not work.","A possible customer changes their mind.","You find an existing competitor.","Interest is lower than you expected.","A person asks for a service you have not offered.","Your first proposal gets mixed feedback."], ["Ask questions and look for evidence behind the response.","Improve the quality or reliability of the offer.","Test a different version on a small scale.","Discuss the feedback with a trusted collaborator."]],
    [["You have limited time and money for an idea.","You need equipment before you can begin.","A project might interfere with your studies.","You are unsure what a service will cost to deliver.","A plan depends on unreliable transport.","You must decide whether to commit more resources."], ["Clarify costs, constraints and unanswered questions.","Make sure I can meet the commitments I already have.","Set a small budget and a clear stopping point.","Look for shared resources and practical support."]],
    [["You organise the first week of a project.","You receive more requests than expected.","A delivery takes longer than planned.","Someone asks for a change at short notice.","You need to explain your offer clearly.","You are preparing to hand work to another person."], ["Check the requirements before deciding what to promise.","Use a clear process and keep track of commitments.","Try a manageable change and measure the result.","Agree on responsibilities and communicate early."]],
    [["You compare employment with self-employment.","You decide whether to continue a side project.","You review a project that earned little money.","You are offered a chance to join someone else's venture.","You consider developing a business skill next.","You imagine your preferred way to build experience."], ["I want evidence about the daily work and trade-offs.","I want to build a dependable track record first.","I want room to explore with limited downside.","I want colleagues or mentors I can learn alongside."]],
  ]),
  bank("study", "Study readiness & habits", "Explore planning, practice, help-seeking and study conditions before your next learning step.", {planning:"Planning",practice:"Active practice",support:"Help-seeking",conditions:"Study conditions"}, [
    [["You have several assessments in the same week.","You begin a new term.","You start a longer assignment.","You have fallen behind in one subject.","You prepare for a practical assessment.","You return to studying after a break."], ["Break the work into sessions with realistic deadlines.","Start with a short task to see what I can do.","Ask what support or clarification is available.","Arrange a workable place, time and materials."]],
    [["You have a difficult topic to revise.","You want to check your understanding.","You prepare for a test without a study guide.","You need to remember a process next month.","You revise after receiving feedback.","You want to avoid last-minute cramming."], ["Schedule spaced reviews of the topic.","Recall and apply the material without my notes.","Ask a teacher or peer about the gaps I notice.","Reduce distractions and prepare the resources I need."]],
    [["Your internet access is unreliable.","Your study space is noisy.","Travel leaves you with little time.","Family responsibilities interrupt your routine.","You lack a textbook or device.","You are too tired to concentrate well."], ["Adjust the workload and timetable to what is realistic.","Choose one useful task I can do with what I have.","Ask about accessible alternatives or practical help.","Prioritise the conditions that make study possible."]],
    [["You receive a lower mark than expected.","You cannot understand an instruction.","You have missed an important lesson.","You make repeated mistakes in practice.","You feel stuck on a large assignment.","You do not know how to begin exam revision."], ["Make a recovery plan with one clear next step.","Attempt a small example and inspect my mistakes.","Ask a specific question and act on the answer.","Check whether time, tools or distractions are blocking me."]],
    [["You consider university or TVET study.","You prepare for more independent learning.","You compare online with classroom learning.","You plan a week with fewer reminders from teachers.","You evaluate your current study routine.","You choose one habit to improve this month."], ["I would focus on planning and following through.","I would focus on practising and checking understanding.","I would focus on finding and using support early.","I would focus on sustainable study conditions."]],
  ]),
  bank("decisions", "Career decisions & confidence", "Find your next useful step through evidence, experiments, conversations and reflection.", {evidence:"Evidence gathering",testing:"Trying things",conversation:"Conversation",reflection:"Personal reflection"}, [
    [["You have several possible careers in mind.","A new career idea catches your attention.","You do not recognise many job titles.","You hear conflicting advice about a route.","You begin making a study shortlist.","You want to narrow a broad area of interest."], ["Research what the work and entry routes involve.","Try a small activity related to the work.","Talk to someone who knows the route.","Write down what attracts me and what worries me."]],
    [["A career sounds exciting on social media.","Someone promises an easy route to success.","A family member strongly recommends a profession.","You read a salary claim without a source.","A course advert sounds too good to be true.","You hear that a field has no future."], ["Check the claim against reliable current sources.","Explore the actual tasks before judging the title.","Ask people in the field about their experience.","Separate what I want from what other people expect."]],
    [["You worry about choosing the wrong subjects.","A qualification seems financially difficult.","You are uncertain about moving away to study.","Your marks differ from a programme requirement.","You need an alternative if your first plan fails.","You are unsure how long a route will take."], ["Compare requirements, costs and alternatives.","Test a practical next step before committing further.","Discuss the constraint with an adviser or supporter.","Clarify which trade-offs I can realistically accept."]],
    [["You have two equally appealing options.","You have researched a route but still feel unsure.","You keep changing your shortlist.","An application deadline is approaching.","You are considering a direction unlike your friends'.", "You need to choose what to investigate next."], ["List the unanswered questions that matter most.","Choose a manageable trial with a review date.","Talk through my reasoning with someone I trust.","Compare the options against my own priorities."]],
    [["You finish a job-shadowing experience.","You complete a short course.","You speak to someone working in a field.","You receive a disappointing application result.","You realise your interests have changed.","You review your career plan at the end of term."], ["Update my understanding with the new information.","Choose the next small activity to explore.","Discuss what I learned and ask for perspective.","Reflect on what felt energising, difficult or meaningful."]],
  ]),
];

export function extraChoiceQuestions(rows: string[][], signals: string[]): SuiteQuestion[] {
  return rows.map(([prompt, ...labels]) => ({ prompt, options: labels.map((label, i) => ({ label, signal: signals[i] })) }));
}
