import Link from "next/link";
import { Reggie } from "@/components/reggie";
import { readWorkspace } from "@/lib/workspace-server";
import CheckoutButton from "./purchase-button";
export const metadata={title:"Choose your path | Pathfinder SA"};
export const dynamic="force-dynamic";
export default async function UpgradePage(){
  const state=await readWorkspace();
  return <main className="upgrade-page"><Link href="/" className="eyebrow">← PATHFINDER SA</Link><div className="upgrade-heading"><div><span className="eyebrow">YOUR PERSONAL WORKSPACE</span><h1>A little direction.<br/>A lot of possibility.</h1><p>Every paid package includes a private dashboard, saved reports for students, parents or schools, and three editable CV templates.</p></div><Reggie size={135} message="Your results belong to you. You choose who sees them."/></div>{state&&state.tier!=="free"&&<p className="workspace-notice">Your {state.tier==="full"?"Trailblazer":"Hatchling"} package is active. <Link href="/dashboard">Open your dashboard →</Link></p>}<div className="upgrade-grid">{([{id:"start",name:"Hatchling",price:249,detail:"Start with your interests and build a practical first plan.",items:["Complete career direction assessment","Core career and university shortlist","Student, parent and school report formats","CV studio: three templates, save and PDF export"]},{id:"full",name:"Trailblazer",price:699,detail:"Explore your subjects, strengths and next steps in more depth.",items:["All six assessments and saved profiles","All 32 career profiles and 16 institutions","Reports across your completed assessments","CV studio and a personal action checklist"]}] as const).map(plan=><article key={plan.id}><Reggie variant={plan.id==="start"?"hatchling":"trailblazer"} size={100}/><h2>{plan.name}</h2><strong className="plan-price">R{plan.price}<small>once-off</small></strong><p>{plan.detail}</p><ul>{plan.items.map(i=><li key={i}>✓ {i}</li>)}</ul><CheckoutButton tier={plan.id} signedIn={!!state} available={!!process.env.PAYSTACK_SECRET_KEY?.startsWith("sk_live_")}/></article>)}</div><p className="workspace-note">Use the same account across devices. Access activates after Paystack confirms a successful live payment. <Link href="/dashboard/demo">Explore the dashboard demo</Link>.</p><p className="workspace-note">Have a receipt from our <a href="https://paystack.shop/pay/pathfindersa">original R699 payment page</a>? <Link href="/payment/complete">Get payment help</Link>.</p></main>;
}
