"use client";
import { useMemo, useState } from "react";
import dynamic from "next/dynamic";
const ResponseChart = dynamic(() => import("@/components/response-chart"), {loading: () => <div className="chart-loading">Loading response chart…</div>});
import Image from "next/image";
import Link from "next/link";
import { ArrowLeft, ArrowRight, Brain, Check, Clock3, LockKeyhole, RotateCcw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { Reggie } from "@/components/reggie";
import type { SuiteAssessment } from "@/lib/assessment-suite";
import { saveSuiteResult } from "@/app/dashboard/actions";
const PAYSTACK_URL="/upgrade";
export default function AssessmentSuiteClient({tier,assessments:assessmentSuite}:{tier:"free"|"start"|"full";assessments:(SuiteAssessment & {totalQuestions:number})[]}){
  const [saveMessage,setSaveMessage]=useState(""); const [saving,setSaving]=useState(false);
  async function saveResult(){if(!active)return;setSaving(true);try{const result=await saveSuiteResult({id:active.id,answers:active.questions.map((_,i)=>answers[i])});setSaveMessage(result.error??result.message??"");}catch{setSaveMessage("Saving failed. Please try again.");}finally{setSaving(false);}}
  const [activeId,setActiveId]=useState<string|null>(null); const [step,setStep]=useState(0); const [answers,setAnswers]=useState<Record<number,string>>({});
  const active=assessmentSuite.find(item=>item.id===activeId);
  const result=useMemo(()=>{if(!active)return[];const counts:Record<string,number>={};Object.values(answers).forEach(v=>counts[v]=(counts[v]??0)+1);return Object.entries(counts).sort((a,b)=>b[1]-a[1]).map(([key,value])=>({key,label:active.signals[key]??key,value}));},[active,answers]);
  function start(id:string){setActiveId(id);setSaveMessage("");setStep(0);setAnswers({});window.scrollTo({top:0,behavior:"smooth"});}
  if(active){const locked=active.id==="career"?tier==="free":tier!=="full";const sampleLimit=active.id==="career"?3:1;const question=active.questions[step];const complete=step>=active.questions.length;return <main className="suite-page"><header className="suite-nav"><Link href="/"><Image src="/pathfinder-logo.png" width={42} height={42} alt="Pathfinder SA logo"/><b>Pathfinder SA</b></Link><button onClick={()=>setActiveId(null)}><ArrowLeft/>All assessments</button></header>{locked&&step>=sampleLimit?<section className="suite-lock"><Reggie size={150} message="You had a peek. Trailblazer opens the whole route."/><LockKeyhole/><p className="eyebrow">TRAILBLAZER</p><h1>Continue the complete {active.title} assessment.</h1><p>Your sample is complete. Trailblazer unlocks every question, full results and the complete career and university research library.</p><Button asChild size="lg"><a href={PAYSTACK_URL}>Become a Trailblazer for R699 <ArrowRight/></a></Button></section>:complete?<section className="suite-results"><p className="eyebrow">YOUR RESULTS</p><h1>{active.title} profile</h1><p>Your strongest signals are a starting point for reflection, not a diagnosis or prediction.</p><ResponseChart signals={result.map(item=>({key:item.key,label:item.label,count:item.value}))} total={active.questions.length} label={`${active.title} signals`}/>{active.id==="subjects"&&<div className="subject-result"><h2>Subject groups to investigate</h2><p>Keep the top two signal groups open while you compare school availability and current university entry requirements. Mathematics keeps more quantitative routes open, but the right choice depends on your marks, support and intended programmes.</p></div>}<p role="status">{saveMessage}</p><div className="suite-actions"><Button disabled={saving} onClick={saveResult}>{saving?"Saving…":"Save to my reports"}</Button><Button asChild variant="outline"><Link href="/dashboard">Dashboard</Link></Button><Button variant="outline" onClick={()=>{setStep(0);setAnswers({});}}><RotateCcw/>Retake</Button><Button asChild><Link href="/#careers">Explore career samples <ArrowRight/></Link></Button></div></section>:<section className="suite-question"><div className="question-meta"><span>{active.title}</span><span>{step+1} / {active.questions.length}</span></div><Progress value={(step+1)/active.questions.length*100}/><p>Choose the response closest to what you would actually do.</p><h1>{question.prompt}</h1><div className="suite-options">{question.options.map(option=><button className={answers[step]===option.signal?"selected":""} key={option.label} onClick={()=>setAnswers({...answers,[step]:option.signal})}>{option.label}<Check/></button>)}</div><div className="suite-actions"><Button variant="outline" disabled={step===0} onClick={()=>setStep(step-1)}><ArrowLeft/>Back</Button><Button disabled={!answers[step]} onClick={()=>setStep(step+1)}>{step+1===active.questions.length?"See my results":"Next"}<ArrowRight/></Button></div></section>}</main>}
  return <main className="suite-page"><header className="suite-nav"><Link href="/"><Image src="/pathfinder-logo.png" width={42} height={42} alt="Pathfinder SA logo"/><b>Pathfinder SA</b></Link><Link href="/account">Account</Link></header><section className="suite-intro"><p className="eyebrow">ASSESSMENT CENTRE</p><h1>Understand the whole person behind the choice.</h1><p>Start with the free career sample, then use Trailblazer for subject choices, leadership, work style, learning and emotional intelligence.</p></section><div className="suite-grid">{assessmentSuite.map((item,index)=>{const locked=item.id==="career"?tier==="free":tier!=="full";return <article key={item.id}><span className="suite-number">0{index+1}</span><Brain/><h2>{item.title}</h2><p>{item.description}</p><small><Clock3/>{item.duration} · {item.totalQuestions} questions</small>{locked&&<span className="premium-pill"><LockKeyhole/>{item.id==="career"?"Hatchling or Trailblazer":"Trailblazer"}</span>}<Button variant={index===0?"default":"outline"} onClick={()=>start(item.id)}>{locked?item.id==="career"?"Try three sample questions":"Try one sample question":"Start assessment"}<ArrowRight/></Button></article>})}</div></main>
}
