import Link from "next/link";
import { ArrowRight, BookOpen, Check, FileText, GraduationCap, HeartHandshake, School, Target, Users } from "lucide-react";
import { Reggie } from "./reggie";
export const audiences = {
  students: { label:"For students", kicker:"YOUR FUTURE, AT YOUR PACE", title:"You don’t need every answer. Just a next step.", intro:"Turn your interests into a plan you can actually use. Explore subjects, compare careers and build the confidence to take your first step.", icon:GraduationCap, steps:["Discover what interests you","Connect subjects to possible paths","Build a shortlist and a first CV"], features:[{title:"Get to know yourself",text:"Start with career interests. Trailblazer adds subject choices, leadership, personality, learning preferences and EQ reflection."},{title:"Explore the possibilities",text:"Read about daily work, training routes and the subjects to investigate. Compare institutions and follow their official links before deciding."},{title:"Bring your next step to life",text:"Save your results, use a practical checklist and create a CV for a bursary, internship or first opportunity."}] },
  parents: { label:"For parents", kicker:"SUPPORT WITHOUT THE PRESSURE", title:"A better conversation about what comes next.", intro:"Help your child explore their own direction. Make space for their interests, understand the options together and turn uncertainty into a manageable family plan.", icon:HeartHandshake, steps:["Listen to their interests","Read a plain-language report together","Agree on one practical next step"], features:[{title:"Understand their perspective",text:"A parent report reframes the learner’s completed assessments into conversation prompts and areas to explore together."},{title:"Make choices with context",text:"Discuss subject availability, marks, costs, travel and support. A promising route still needs a practical plan."},{title:"Let them lead the sharing",text:"The learner chooses when to export their report. Parent reports do not create automatic access to the learner’s account."}] },
  schools: { label:"For schools", kicker:"MAKE GUIDANCE A CONVERSATION", title:"Give every learner a starting point for direction.", intro:"Bring structure to individual career conversations. Use learner-shared reports to connect interests, subject choices and achievable next steps.", icon:School, steps:["Invite the learner to reflect","Discuss their shared report","Agree on actions and a review date"], features:[{title:"Ready for a guidance session",text:"The school report summarises completed assessments, suggested discussion areas and a simple action plan for a learner–adviser meeting."},{title:"Connect interests to subjects",text:"Explore the learner’s subject choices alongside their school’s actual offerings, marks and current programme requirements."},{title:"Keep the learner in control",text:"Reports are exported by the account holder. Individual packages do not include school-wide rosters, cohort analytics or access to other learners’ records."}] },
} as const;
export type Audience = keyof typeof audiences;
export function AudienceGraphic({audience}:{audience:Audience}) {
 const data=audiences[audience];const Icon=data.icon;
 return <div className={`audience-graphic graphic-${audience}`} aria-label={`${data.label}: illustrated guidance journey`}><div className="graphic-orbit"/><span className="graphic-stamp"><Icon size={30}/></span><div className="graphic-paper"><span className="eyebrow">{audience==="students"?"MY NEXT CHAPTER":audience==="parents"?"LET’S TALK ABOUT YOUR FUTURE":"LEARNER GUIDANCE PLAN"}</span><h3>{audience==="students"?"A path that feels like you.":audience==="parents"?"Explore it. Together.":"Small steps. Clear direction."}</h3>{data.steps.map((s,i)=><div className="graphic-step" key={s}><span>{i+1}</span>{s}<Check size={14}/></div>)}<div className="graphic-tags"><span><FileText size={13}/>Reports</span><span><Target size={13}/>Next steps</span></div></div><div className="graphic-note"><Users size={18}/><span>{audience==="students"?"Your choices. Your pace.":"A shared conversation, a personal path."}</span></div><Reggie variant={audience==="students"?"hatchling":"trailblazer"} size={95}/></div>;
}
export function AudienceCards(){return <section id="who-its-for" className="signal-section audience-section"><div className="section-lead"><span>ONE PATH. A CIRCLE OF SUPPORT.</span><h2>Built for the people<br/>behind the next step.</h2><p>Different perspectives, one shared aim: helping a young person find a direction that makes sense for them.</p></div><div className="audience-cards">{(Object.keys(audiences) as Audience[]).map(key=>{const a=audiences[key];return <article key={key}><AudienceGraphic audience={key}/><div className="audience-card-copy"><h3>{a.label}</h3><p>{a.intro}</p><Link href={`/solutions/for-${key}`}>Explore {a.label.toLowerCase()} <ArrowRight size={18}/></Link></div></article>})}</div></section>}
export function AudiencePage({audience}:{audience:Audience}){const a=audiences[audience];return <main className="audience-page"><header className="audience-nav"><Link href="/" className="signal-logo">Pathfinder <b>SA</b></Link><nav>{(Object.keys(audiences) as Audience[]).map(key=><Link aria-current={audience===key?"page":undefined} key={key} href={`/solutions/for-${key}`}>{audiences[key].label}</Link>)}</nav><Link className="workspace-button" href="/dashboard">My dashboard →</Link></header><section className="audience-hero"><div><p className="eyebrow">{a.kicker}</p><h1>{a.title}</h1><p>{a.intro}</p><div className="audience-actions"><Link className="workspace-button" href={audience==="students"?"/assessments":"/dashboard/demo"}>{audience==="students"?"Start a free sample":"Explore the dashboard demo"} <ArrowRight size={18}/></Link><Link href="/#pricing">See the packages</Link></div></div><AudienceGraphic audience={audience}/></section><section className="audience-features">{a.features.map((f,i)=><article key={f.title}><span className="feature-number">0{i+1}</span><h2>{f.title}</h2><p>{f.text}</p></article>)}</section><section className="audience-report"><div className="report-illustration"><FileText size={32}/><span>PATHFINDER · PERSONAL GUIDANCE REPORT</span><h3>{audience==="schools"?"From reflection to a plan.":audience==="parents"?"More understanding. Less guessing.":"Your next chapter starts here."}</h3><div className="illustration-lines"><i/><i/><i/></div><div><span><BookOpen/>Assessment insights</span><span><Check/>Actions to discuss</span></div><small>Illustration · reports use your saved results</small></div><div><p className="eyebrow">INSIGHT YOU CAN TAKE WITH YOU</p><h2>A report for the right conversation.</h2><p>Switch between student, parent and school formats in your paid dashboard. Export a printable PDF, then choose who to share it with.</p><p>Keep building with three CV layouts: Classic, Modern and Graduate. Add education, projects, experience and achievements, and save your work to your account.</p><Link className="workspace-button" href="/dashboard/demo">Try the workspace demo <ArrowRight size={18}/></Link></div></section><footer className="signal-footer"><p>Pathfinder SA · Every next step starts somewhere.</p><nav><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link><a href="mailto:pathfinderzar@gmail.com">Get in touch</a></nav></footer></main>}
