import Link from "next/link";
import { adminUserDetail } from "@/lib/admin-server";
import { formatDate, accountStatus, tierName, entitlementStatus } from "@/lib/entitlements";
import { profileSchema } from "@/lib/profile";
import { assess, parseAssessmentDraft } from "@/lib/assessment";
import { assessmentSuite } from "@/lib/assessment-suite";
import { resultSchema } from "@/lib/result-schema";
import { z } from "zod";
import AccessControl from "../../access-controls";
import LegacyProfile from "../../legacy-profile";

const labels: Record<string, string> = { displayName: "Name", lifeStage: "Life stage", birthYear: "Birth year", province: "Province", mobility: "Mobility", goal: "Goal", grade: "Grade", subjects: "Subjects", marks: "Marks", institution: "Institution", qualification: "Qualification", year: "Year of study", experience: "Experience", role: "Current role", yearsExperience: "Years of experience", enjoy: "Enjoys", change: "Wants to change", consent: "Onboarding consent" };
export default async function UserProfile({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const { user, records, entitlements, products, audit, legacyProfile, legacyStudent } = await adminUserDetail(id);
  const profile = profileSchema.safeParse(records.pathfinder_profile ?? legacyProfile?.profile);
  const results = z.array(resultSchema).max(10).safeParse(records.pathfinder_results).data ?? [];
  let draft = null;
  try { if (records.pathfinder_draft) draft = parseAssessmentDraft(records.pathfinder_draft); } catch { /* An older incompatible draft remains untouched. */ }
  const recommendations = draft?.completed ? assess(draft).matches : [];
  return <><Link href="/admin/users" className="back-link">← All users</Link><header className="admin-heading"><p className="eyebrow">USER PROFILE</p><h1>{profile.success ? profile.data.displayName : user.display_name || "Pathfinder account"}</h1><p>{user.email}</p><span className="admin-id">{user.user_id}</span></header>
    <div className="admin-profile-grid"><section className="admin-panel"><h2>Account & onboarding</h2><dl className="admin-details"><dt>Joined</dt><dd>{formatDate(user.joined_at)} SAST</dd><dt>Current access</dt><dd>{tierName(user.access_tier)}</dd><dt>Email</dt><dd>{user.email_confirmed ? "Verified" : "Awaiting verification"}</dd><dt>Account</dt><dd>{accountStatus(user)}</dd>{profile.success && Object.entries(profile.data).filter(([key]) => key in labels).map(([key, value]) => <div className="admin-detail-row" key={key}><dt>{labels[key]}</dt><dd>{typeof value === "boolean" ? value ? "Accepted" : "No" : String(value)}</dd></div>)}</dl>{!profile.success && <p className="admin-empty">No completed Pathfinder profile is available.</p>}{legacyStudent && <LegacyProfile data={legacyStudent.onboarding} />}</section>
    <section className="admin-panel"><h2>Assessments</h2><p>{results.length} saved assessment{results.length === 1 ? "" : "s"}. Original interest assessment: {draft ? draft.completed ? "completed" : "in progress" : "not started"}.</p>{results.map(result => <details className="admin-result" key={result.id}><summary>{assessmentSuite.find(a => a.id === result.id)?.title ?? result.id} <small>{formatDate(result.completedAt)}</small></summary><dl className="admin-details">{result.scores.map(score => <div className="admin-detail-row" key={score.key}><dt>{score.label}</dt><dd>{score.count} / {result.total} responses</dd></div>)}</dl></details>)}{legacyStudent && <LegacyProfile data={legacyStudent.assessment} assessment />}<h3>Career recommendations</h3>{recommendations.length ? <ul>{recommendations.map(match => <li key={match.career.id}><strong>{match.career.title}</strong><p>{match.career.work}</p></li>)}</ul> : <p>No saved personalised career recommendations are available from the original assessment. Completed assessment signals are shown above.</p>}</section></div>
    <section className="admin-panel"><div className="admin-section-heading"><div><h2>Products & entitlements</h2><p>Access is the combined benefit of all active products.</p></div><AccessControl userId={id} email={user.email ?? id} products={products} /></div>{!entitlements.length && <p className="admin-empty">This account has no products yet.</p>}{entitlements.map(item => <article className="admin-entitlement" key={item.id}><div className="admin-section-heading"><h3>{item.pathfinder_products.name} <span className={`admin-badge ${entitlementStatus(item)}`}>{entitlementStatus(item)}</span></h3><AccessControl userId={id} email={user.email ?? id} revoked={item.status === "revoked"} entitlement={{ id: item.id, name: item.pathfinder_products.name }} /></div><dl className="admin-details"><dt>Source</dt><dd>{item.source.replaceAll("_", " ")}</dd><dt>Granted</dt><dd>{formatDate(item.granted_at)} · {item.granted_by ? <Link href={`/admin/users/${item.granted_by}`}>{item.granted_by}</Link> : "System / imported"}</dd><dt>Expiry</dt><dd>{item.expires_at ? `${formatDate(item.expires_at)} SAST` : "No expiry"}</dd>{item.revoked_at && <><dt>Revoked</dt><dd>{formatDate(item.revoked_at)} · {item.revoked_by ?? "System"}</dd></>}</dl></article>)}</section>
    <section className="admin-panel"><h2>Access history</h2><p>Dates are shown in South African Standard Time. Internal notes are visible only to admins.</p>{audit.length ? <ol className="admin-history">{audit.map(event => <li key={event.id}><strong>{entitlements.find(e => e.id === event.entitlement_id)?.pathfinder_products.name} · {event.action}</strong><span>{formatDate(event.occurred_at)} · {event.actor_id ? <Link href={`/admin/users/${event.actor_id}`}>{event.actor_id}</Link> : "System / imported"}</span>{event.note && <p>{event.note}</p>}</li>)}</ol> : <p className="admin-empty">No access changes recorded.</p>}</section></>;
}
