import fs from 'node:fs/promises';
import sharp from 'sharp';
const sources={uct:'https://uct.ac.za/themes/custom/blip_uct/logo.svg',wits:'https://www.wits.ac.za/media/wits-university-style-assets/images/wits-logo.svg',ukzn:'https://ukzn.ac.za/wp-content/uploads/2020/03/Transp_bg.png',nwu:'https://www.nwu.ac.za/sites/www.nwu.ac.za/files/NWU-logo-pers_1.png',dut:'https://www.dut.ac.za/wp-content/uploads/2026/03/DUT-Logo_new-1.png',tut:'https://www.tut.ac.za/media/tshwane-interim/site-assets/images/tut-logo.svg',unisa:'https://www.unisa.ac.za/static/corporate_web/Content/Temporary/unisa_logo_tagline.svg',ufs:'https://www.ufs.ac.za/images/librariesprovider5/ufs_redesign_2021/ufsheaderlogo.svg?sfvrsn=15b37820_3',rhodes:'https://www.ru.ac.za/media/rhodesuniversity/styleassets/2019v6/images/RU_Logo_1.png',nmu:'https://www.mandela.ac.za/App_Themes/global/images/logo-white.png',vut:'https://vut.ac.za/wp-content/uploads/2026/03/Vaal-University-of-Technology-60th-logo-scaled.webp',uwc:'https://uwc-za.b-cdn.net/files/images/UWC-2025-trilingual-landscape.svg',uj:'https://ujcontent.uj.ac.za/rep/esploro/lightLogo?institution=27UOJ_INST'};
await fs.mkdir('public/universities',{recursive:true});
const manifest={};
await Promise.all(Object.entries(sources).map(async([id,url])=>{try{const r=await fetch(url,{signal:AbortSignal.timeout(25000)});if(!r.ok)throw new Error(`HTTP ${r.status}`);const b=Buffer.from(await r.arrayBuffer());await sharp(b,{density:200}).resize({width:900,height:350,fit:'inside',withoutEnlargement:true}).png().toFile(`public/universities/${id}.png`);manifest[id]={source:url,verified:'2026-09-06',darkBackground:id==='nmu',file:`/universities/${id}.png`};console.log(id,'saved');}catch(e){console.log(id,e.message);}}));
await fs.writeFile('research/logo-sources.json',JSON.stringify(manifest,null,2));
for(const [id,url] of Object.entries({stellenbosch:'https://www.su.ac.za/en/about/brand-identity',up:'https://www.up.ac.za/university-of-pretoria-brand',cput:'https://cput.ac.za/study-at-cput/postgraduate/apply'})){try{const r=await fetch(url,{signal:AbortSignal.timeout(20000)});const html=await r.text();await fs.writeFile(`research/logos/${id}-brand.html`,html);console.log(id,r.status,[...html.matchAll(/<(?:img|source)\b[^>]*>/gi)].map(x=>x[0]).filter(x=>/logo|crest/i.test(x)).slice(0,8).join('\n'));}catch(e){console.log(id,e.message,e.cause?.code);}}
const changelog=await fetch('https://supabase.com/changelog.md').then(r=>r.text());await fs.writeFile('research/supabase-changelog.md',changelog);console.log('Changelog downloaded',changelog.slice(0,300));
